baseURL: /
languageCode: en-us
title: Jake Jarvis

# increase timeout for image processing (3 minutes)
timeout: 180000

canonifyURLs: true

enableRobotsTXT: true
enableInlineShortcodes: true
enableGitInfo: true

# as of v0.73.0: taxonomy => term, taxonomyTerm => taxonomy
# https://github.com/gohugoio/hugo/releases/tag/v0.73.0
disableKinds:
  - taxonomy
  - term

# don't worry, inserted manually :)
disableHugoGeneratorInject: true

# prefer 301 server redirects, see vercel.json
disableAliases: true

pygmentsUseClasses: true
pygmentsCodeFences: true
pygmentsCodeFencesGuessSyntax: false

params:
  # different from baseURL above, this is only used where absolute URLs are necessary: (no trailing slash!)
  baseURL: https://jarv.is
  description: Hi there! I'm a frontend web developer based in Boston, Massachusetts specializing in the JAMstack, modern JavaScript frameworks, and progressive web apps.
  image: images/logo.png # relative to assetDir root
  mainSection: notes # content that appears in feeds
  theme:
    maxWidth: 865 # px
    defaultTheme: light # light or dark?
  license:
    name: CC-BY-4.0
    nameLong: Creative Commons Attribution 4.0 International
    copyrightFirstYear: 2001
  social:
    githubRepo: jakejarvis/jarv.is # user/repo
    webmentionIO: jarv.is # webmention.io username
    facebookAppID: 3357248167622283
  algolia:
    vars:
      - title
      - summary
      - date
      - permalink
      - draft

author:
  name: Jake Jarvis
  image: images/me.jpg # relative to assetDir root
  email: jake@jarv.is
  monetization: $ilp.uphold.com/BJp6d2FrEB69 # Uphold ILP wallet: https://support.uphold.com/hc/en-us/articles/360043227832-How-to-find-your-ILP-address-Interledger-payment-pointer-
  social:
    github: jakejarvis
    keybase: jakejarvis
    twitter: jakejarvis
    twitterID: 229769022
    medium: jakejarvis
    linkedin: jakejarvis
    facebook: jakejarvis
    facebookID: 1329090853
    instagram: jakejarvis
    mastodon: mastodon.social/@jakejarvis

menu:
  main:
    - name: Home
      pre: 🏡
      url: /
      weight: 1
    - name: Notes
      pre: 🗒
      url: /notes/
      weight: 2
    - name: Projects
      pre: 👨‍💻
      url: /projects/
      weight: 3
    - name: Contact
      pre: 📬
      url: /contact/
      weight: 4

frontmatter:
  lastmod:
    - date
    - publishDate
    - :default

sitemap:
  filename: sitemap.xml

outputs:
  home:
    - html
    - rss
    - atom
    - manifest
    - algolia
  section:
    - html
  page:
    - html

outputFormats:
  rss:
    mediaType: application/rss
    baseName: feed # /feed.xml
    isPlainText: false
    isHTML: false
  atom:
    mediaType: application/atom+xml
    baseName: feed # /feed.atom
    isPlainText: false
    isHTML: false
  manifest:
    mediaType: application/manifest+json # https://github.com/w3c/manifest/issues/689
    baseName: site # /site.webmanifest
    isPlainText: true
    notAlternative: true
  algolia:
    mediaType: application/json
    baseName: algolia # /algolia.json
    isPlainText: true
    notAlternative: true

mediaTypes:
  application/atom+xml:
    suffixes:
      - atom
  application/manifest+json:
    suffixes:
      - webmanifest

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    extensions:
      linkify: false
      strikethrough: true
      typographer: false
    parser:
      autoHeadingID: false
    renderer:
      unsafe: true
  highlight:
    codeFences: true
    guessSyntax: false
    lineNos: true
    lineNumbersInTable: true
    noClasses: true
    tabWidth: 4

imaging:
  # options for resampling filters:
  # https://github.com/disintegration/imaging#image-resizing
  resampleFilter: lanczos
  # let imagemin do all the heavy lifting post-build.
  # can be overridden (overrode?) inline for individual JPEGs:
  # https://gohugo.io/content-management/image-processing/#jpeg-quality
  quality: 100

build:
  # don't use cache for SCSS compilation, better to throw error than be stale
  useResourceCacheWhen: never

caches:
  # commit things like oEmbed JSON (tweets, etc.) next to resources in this repo
  assets:
    dir: :cacheDir/:project # default: :resourceDir/_gen
  getcsv:
    dir: :resourceDir/_gen # default: :cacheDir/:project
  getjson:
    dir: :resourceDir/_gen # default: :cacheDir/:project
  images:
    dir: :resourceDir/_gen
  modules:
    dir: :cacheDir/modules
