import type { MDXComponents } from "mdx/types";

import Image from "@/components/image";
import Link from "@/components/link";
import CodeBlock from "@/components/code-block";
import Video from "@/components/video";
import Bluesky from "@/components/third-party/bluesky";
import Tweet from "@/components/third-party/tweet";
import YouTube from "@/components/third-party/youtube";
import Gist from "@/components/third-party/gist";
import CodePen from "@/components/third-party/codepen";

export const useMDXComponents = (components: MDXComponents): MDXComponents => {
  return {
    ...components,

    // direct replacements for HTML tags generated by remark:
    img: Image,
    a: Link,
    pre: CodeBlock,

    // third-party embeds:
    Video,
    Bluesky,
    Tweet,
    YouTube,
    Gist,
    CodePen,
  };
};
