import type { MDXComponents } from "mdx/types";

import Link from "@/components/link";
import CodeBlock from "@/components/code-block";
import Image from "@/components/image";
import Video from "@/components/video";
import Bluesky from "@/components/third-party/bluesky";
import Tweet from "@/components/third-party/tweet";
import YouTube from "@/components/third-party/youtube";
import Gist from "@/components/third-party/gist";
import CodePen from "@/components/third-party/codepen";

export const useMDXComponents = (components: MDXComponents): MDXComponents => {
  return {
    ...components,

    // direct replacements for HTML tags generated by remark:
    a: Link,
    pre: CodeBlock,
    code: (props) => (
      // only applies to inline code, *not* highlighted code blocks!
      <code className="bg-muted relative rounded-sm px-[0.3rem] py-[0.2rem] text-sm font-medium" {...props} />
    ),
    img: (props) => (
      // eslint-disable-next-line jsx-a11y/alt-text
      <Image
        className="[&+em]:text-muted-foreground my-8 rounded-md [&+em]:-mt-4 [&+em]:block [&+em]:text-center [&+em]:text-[0.875em] [&+em]:leading-normal [&+em]:font-medium [&+em]:not-italic"
        {...props}
      />
    ),
    figure: (props) => <figure className="my-8 [&>*]:my-0" {...props} />,
    figcaption: (props) => (
      <figcaption className="text-muted-foreground mt-3.5 text-[0.875em] leading-snug" {...props} />
    ),
    blockquote: (props) => (
      <blockquote className="border-border text-muted-foreground mt-6 border-l-4 pl-4" {...props} />
    ),
    h1: (props) => (
      <h1
        className="mt-6 mb-4 scroll-m-4 text-3xl leading-snug font-extrabold md:text-4xl [&_strong]:font-black [&+*]:mt-0"
        {...props}
      />
    ),
    h2: (props) => (
      <h2
        className="mt-6 mb-4 scroll-m-4 text-xl leading-snug font-bold first:mt-0 md:text-2xl [&_code]:text-[0.875em] [&_strong]:font-extrabold [&+*]:mt-0"
        {...props}
      />
    ),
    h3: (props) => (
      <h3
        className="mt-6 mb-2.5 scroll-m-4 text-lg leading-relaxed font-semibold md:text-xl [&_code]:text-[0.9em] [&_strong]:font-bold [&+*]:mt-0"
        {...props}
      />
    ),
    h4: (props) => (
      <h4 className="mt-6 mb-2 scroll-m-4 leading-normal font-semibold [&_strong]:font-bold [&+*]:mt-0" {...props} />
    ),
    ul: (props) => <ul className="my-5 list-disc pl-7 [&>li]:pl-1.5" {...props} />,
    ol: (props) => <ol className="my-5 list-decimal pl-7 [&>li]:pl-1.5" {...props} />,
    li: (props) => (
      <li
        className="[&::marker]:text-muted-foreground my-0.5 [&::marker]:font-normal [&>ol]:my-1 [&>ul]:my-1"
        {...props}
      />
    ),
    hr: (props) => <hr className="border-border mx-auto my-6 w-11/12 border-t-2 [&+*]:mt-0" {...props} />,

    // third-party embeds:
    Video,
    Bluesky,
    Tweet,
    YouTube,
    Gist,
    CodePen,
  };
};
