import dynamic from "next/dynamic";

// Bundle these components by default:
import { default as Image } from "../components/Image";
import { default as Figure } from "../components/Figure";

// These (mostly very small) components are direct replacements for HTML tags generated by remark:
import { default as a } from "../components/Link";
import { default as code } from "../components/CodeHybrid";
import { default as blockquote } from "../components/Blockquote";
import { default as hr } from "../components/HorizontalRule";
import { H1 as h1, H2 as h2, H3 as h3, H4 as h4, H5 as h5, H6 as h6 } from "../components/Heading";
import { UnorderedList as ul, OrderedList as ol, ListItem as li } from "../components/List";

// ...and these components are technically passed into all posts, but next/dynamic ensures they're loaded only
// when they're referenced in the individual mdx files.
export const IFrame = dynamic(() => import("../components/IFrame"));
export const Video = dynamic(() => import("../components/Video"));
export const YouTube = dynamic(() => import("../components/YouTubeEmbed"));
export const Tweet = dynamic(() => import("../components/TweetEmbed"));
export const Gist = dynamic(() => import("../components/GistEmbed"));
export const CodePen = dynamic(() => import("../components/CodePenEmbed"));

// One-offs for specific posts:
export const OctocatLink = dynamic(() => import("../components/OctocatLink"));

import type { MDXComponents } from "mdx/types";

export function useMDXComponents(components: MDXComponents): MDXComponents {
  return {
    ...components,
    Image,
    Figure,
    // @ts-ignore
    a,
    code,
    blockquote,
    hr,
    h1,
    h2,
    h3,
    h4,
    h5,
    h6,
    ul,
    ol,
    li,
    IFrame,
    Video,
    YouTube,
    Tweet,
    Gist,
    CodePen,
    OctocatLink,
  };
}
