/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ZipRouteImport } from './routes/zip'
import { Route as UsesRouteImport } from './routes/uses'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PreviouslyRouteImport } from './routes/previously'
import { Route as LicenseRouteImport } from './routes/license'
import { Route as LeoRouteImport } from './routes/leo'
import { Route as HillaryRouteImport } from './routes/hillary'
import { Route as CliRouteImport } from './routes/cli'
import { Route as BirthdayRouteImport } from './routes/birthday'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NotesIndexRouteImport } from './routes/notes/index'
import { Route as SitemapXmlRouteImport } from './routes/sitemap.xml'
import { Route as RobotsTxtRouteImport } from './routes/robots.txt'
import { Route as NotesSlugRouteImport } from './routes/notes/$slug'
import { Route as FeedXmlRouteImport } from './routes/feed.xml'
import { Route as FeedAtomRouteImport } from './routes/feed.atom'
import { Route as ApiHitsRouteImport } from './routes/api/hits'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const ZipRoute = ZipRouteImport.update({
  id: '/zip',
  path: '/zip',
  getParentRoute: () => rootRouteImport,
} as any)
const UsesRoute = UsesRouteImport.update({
  id: '/uses',
  path: '/uses',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviouslyRoute = PreviouslyRouteImport.update({
  id: '/previously',
  path: '/previously',
  getParentRoute: () => rootRouteImport,
} as any)
const LicenseRoute = LicenseRouteImport.update({
  id: '/license',
  path: '/license',
  getParentRoute: () => rootRouteImport,
} as any)
const LeoRoute = LeoRouteImport.update({
  id: '/leo',
  path: '/leo',
  getParentRoute: () => rootRouteImport,
} as any)
const HillaryRoute = HillaryRouteImport.update({
  id: '/hillary',
  path: '/hillary',
  getParentRoute: () => rootRouteImport,
} as any)
const CliRoute = CliRouteImport.update({
  id: '/cli',
  path: '/cli',
  getParentRoute: () => rootRouteImport,
} as any)
const BirthdayRoute = BirthdayRouteImport.update({
  id: '/birthday',
  path: '/birthday',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesIndexRoute = NotesIndexRouteImport.update({
  id: '/notes/',
  path: '/notes/',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapXmlRoute = SitemapXmlRouteImport.update({
  id: '/sitemap/xml',
  path: '/sitemap/xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsTxtRoute = RobotsTxtRouteImport.update({
  id: '/robots/txt',
  path: '/robots/txt',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesSlugRoute = NotesSlugRouteImport.update({
  id: '/notes/$slug',
  path: '/notes/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedXmlRoute = FeedXmlRouteImport.update({
  id: '/feed/xml',
  path: '/feed/xml',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedAtomRoute = FeedAtomRouteImport.update({
  id: '/feed/atom',
  path: '/feed/atom',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHitsRoute = ApiHitsRouteImport.update({
  id: '/api/hits',
  path: '/api/hits',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/birthday': typeof BirthdayRoute
  '/cli': typeof CliRoute
  '/hillary': typeof HillaryRoute
  '/leo': typeof LeoRoute
  '/license': typeof LicenseRoute
  '/previously': typeof PreviouslyRoute
  '/privacy': typeof PrivacyRoute
  '/projects': typeof ProjectsRoute
  '/uses': typeof UsesRoute
  '/zip': typeof ZipRoute
  '/api/hits': typeof ApiHitsRoute
  '/feed/atom': typeof FeedAtomRoute
  '/feed/xml': typeof FeedXmlRoute
  '/notes/$slug': typeof NotesSlugRoute
  '/robots/txt': typeof RobotsTxtRoute
  '/sitemap/xml': typeof SitemapXmlRoute
  '/notes/': typeof NotesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/birthday': typeof BirthdayRoute
  '/cli': typeof CliRoute
  '/hillary': typeof HillaryRoute
  '/leo': typeof LeoRoute
  '/license': typeof LicenseRoute
  '/previously': typeof PreviouslyRoute
  '/privacy': typeof PrivacyRoute
  '/projects': typeof ProjectsRoute
  '/uses': typeof UsesRoute
  '/zip': typeof ZipRoute
  '/api/hits': typeof ApiHitsRoute
  '/feed/atom': typeof FeedAtomRoute
  '/feed/xml': typeof FeedXmlRoute
  '/notes/$slug': typeof NotesSlugRoute
  '/robots/txt': typeof RobotsTxtRoute
  '/sitemap/xml': typeof SitemapXmlRoute
  '/notes': typeof NotesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/birthday': typeof BirthdayRoute
  '/cli': typeof CliRoute
  '/hillary': typeof HillaryRoute
  '/leo': typeof LeoRoute
  '/license': typeof LicenseRoute
  '/previously': typeof PreviouslyRoute
  '/privacy': typeof PrivacyRoute
  '/projects': typeof ProjectsRoute
  '/uses': typeof UsesRoute
  '/zip': typeof ZipRoute
  '/api/hits': typeof ApiHitsRoute
  '/feed/atom': typeof FeedAtomRoute
  '/feed/xml': typeof FeedXmlRoute
  '/notes/$slug': typeof NotesSlugRoute
  '/robots/txt': typeof RobotsTxtRoute
  '/sitemap/xml': typeof SitemapXmlRoute
  '/notes/': typeof NotesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/birthday'
    | '/cli'
    | '/hillary'
    | '/leo'
    | '/license'
    | '/previously'
    | '/privacy'
    | '/projects'
    | '/uses'
    | '/zip'
    | '/api/hits'
    | '/feed/atom'
    | '/feed/xml'
    | '/notes/$slug'
    | '/robots/txt'
    | '/sitemap/xml'
    | '/notes/'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/birthday'
    | '/cli'
    | '/hillary'
    | '/leo'
    | '/license'
    | '/previously'
    | '/privacy'
    | '/projects'
    | '/uses'
    | '/zip'
    | '/api/hits'
    | '/feed/atom'
    | '/feed/xml'
    | '/notes/$slug'
    | '/robots/txt'
    | '/sitemap/xml'
    | '/notes'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/birthday'
    | '/cli'
    | '/hillary'
    | '/leo'
    | '/license'
    | '/previously'
    | '/privacy'
    | '/projects'
    | '/uses'
    | '/zip'
    | '/api/hits'
    | '/feed/atom'
    | '/feed/xml'
    | '/notes/$slug'
    | '/robots/txt'
    | '/sitemap/xml'
    | '/notes/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BirthdayRoute: typeof BirthdayRoute
  CliRoute: typeof CliRoute
  HillaryRoute: typeof HillaryRoute
  LeoRoute: typeof LeoRoute
  LicenseRoute: typeof LicenseRoute
  PreviouslyRoute: typeof PreviouslyRoute
  PrivacyRoute: typeof PrivacyRoute
  ProjectsRoute: typeof ProjectsRoute
  UsesRoute: typeof UsesRoute
  ZipRoute: typeof ZipRoute
  ApiHitsRoute: typeof ApiHitsRoute
  FeedAtomRoute: typeof FeedAtomRoute
  FeedXmlRoute: typeof FeedXmlRoute
  NotesSlugRoute: typeof NotesSlugRoute
  RobotsTxtRoute: typeof RobotsTxtRoute
  SitemapXmlRoute: typeof SitemapXmlRoute
  NotesIndexRoute: typeof NotesIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/zip': {
      id: '/zip'
      path: '/zip'
      fullPath: '/zip'
      preLoaderRoute: typeof ZipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uses': {
      id: '/uses'
      path: '/uses'
      fullPath: '/uses'
      preLoaderRoute: typeof UsesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/previously': {
      id: '/previously'
      path: '/previously'
      fullPath: '/previously'
      preLoaderRoute: typeof PreviouslyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/license': {
      id: '/license'
      path: '/license'
      fullPath: '/license'
      preLoaderRoute: typeof LicenseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leo': {
      id: '/leo'
      path: '/leo'
      fullPath: '/leo'
      preLoaderRoute: typeof LeoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hillary': {
      id: '/hillary'
      path: '/hillary'
      fullPath: '/hillary'
      preLoaderRoute: typeof HillaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cli': {
      id: '/cli'
      path: '/cli'
      fullPath: '/cli'
      preLoaderRoute: typeof CliRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/birthday': {
      id: '/birthday'
      path: '/birthday'
      fullPath: '/birthday'
      preLoaderRoute: typeof BirthdayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes/': {
      id: '/notes/'
      path: '/notes'
      fullPath: '/notes/'
      preLoaderRoute: typeof NotesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap/xml': {
      id: '/sitemap/xml'
      path: '/sitemap/xml'
      fullPath: '/sitemap/xml'
      preLoaderRoute: typeof SitemapXmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots/txt': {
      id: '/robots/txt'
      path: '/robots/txt'
      fullPath: '/robots/txt'
      preLoaderRoute: typeof RobotsTxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes/$slug': {
      id: '/notes/$slug'
      path: '/notes/$slug'
      fullPath: '/notes/$slug'
      preLoaderRoute: typeof NotesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed/xml': {
      id: '/feed/xml'
      path: '/feed/xml'
      fullPath: '/feed/xml'
      preLoaderRoute: typeof FeedXmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed/atom': {
      id: '/feed/atom'
      path: '/feed/atom'
      fullPath: '/feed/atom'
      preLoaderRoute: typeof FeedAtomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/hits': {
      id: '/api/hits'
      path: '/api/hits'
      fullPath: '/api/hits'
      preLoaderRoute: typeof ApiHitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BirthdayRoute: BirthdayRoute,
  CliRoute: CliRoute,
  HillaryRoute: HillaryRoute,
  LeoRoute: LeoRoute,
  LicenseRoute: LicenseRoute,
  PreviouslyRoute: PreviouslyRoute,
  PrivacyRoute: PrivacyRoute,
  ProjectsRoute: ProjectsRoute,
  UsesRoute: UsesRoute,
  ZipRoute: ZipRoute,
  ApiHitsRoute: ApiHitsRoute,
  FeedAtomRoute: FeedAtomRoute,
  FeedXmlRoute: FeedXmlRoute,
  NotesSlugRoute: NotesSlugRoute,
  RobotsTxtRoute: RobotsTxtRoute,
  SitemapXmlRoute: SitemapXmlRoute,
  NotesIndexRoute: NotesIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
